fix(nvim): make markdownlint-cli2 respect global config
This CLI is currently run by 3 different plugins, none-ls, nvim-lint,
and conform.nvim. Remove none-ls as LazyVim isn't using it by default,
so we only need to configure it in nvim-lint for linting.

Also have to rename markdownlint.yaml to .markdownlint.yaml. Not sure
how I missed this when creating this file, but it is never used because
`markdownlint-cli2` requires the dot prefix, even if it's a global file.

```console
❯ markdownlint-cli2 --config ~/.config/markdownlint-cli2/markdownlint.yaml somefile.md
markdownlint-cli2 v0.17.2 (markdownlint v0.37.4)
Error: Unable to use configuration file '/Users/gib/.config/markdownlint-cli2/markdownlint.yaml'; Configuration file should be one of the supported names (e.g., '.markdownlint-cli2.jsonc') or a prefix with a supported name (e.g., 'example.markdownlint-cli2.jsonc').
    at throwForConfigurationFile (file:///Users/gib/.local/share/nvim/mason/packages/markdownlint-cli2/node_modules/markdownlint-cli2/markdownlint-cli2.mjs:37:9)
    at readOptionsOrConfig (file:///Users/gib/.local/share/nvim/mason/packages/markdownlint-cli2/node_modules/markdownlint-cli2/markdownlint-cli2.mjs:178:5)
    at main (file:///Users/gib/.local/share/nvim/mason/packages/markdownlint-cli2/node_modules/markdownlint-cli2/markdownlint-cli2.mjs:941:15)
    ... 3 lines matching cause stack trace ...
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
  [cause]: Error: Configuration file should be one of the supported names (e.g., '.markdownlint-cli2.jsonc') or a prefix with a supported name (e.g., 'example.markdownlint-cli2.jsonc').
      at readOptionsOrConfig (file:///Users/gib/.local/share/nvim/mason/packages/markdownlint-cli2/node_modules/markdownlint-cli2/markdownlint-cli2.mjs:171:13)
      at main (file:///Users/gib/.local/share/nvim/mason/packages/markdownlint-cli2/node_modules/markdownlint-cli2/markdownlint-cli2.mjs:941:15)
      at file:///Users/gib/.local/share/nvim/mason/packages/markdownlint-cli2/node_modules/markdownlint-cli2/markdownlint-cli2-bin.mjs:12:28
      at ModuleJob.run (node:internal/modules/esm/module_job:345:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
}
```

Refs: https://github.com/DavidAnson/markdownlint-cli2/blob/d7a4f7cf4914d3bffb9b83bdbc45fd2a00c91ff9/markdownlint-cli2.mjs#L142-L175