brew: remove python2 as it's apparently no longer available by default
```
❯❯❯   Installing: brew packages.
Warning: 'python2' formula is unreadable: No available formula with the name "python2"
Error: No available formula with the name "python2"
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
Error: No similarly named formulae found.
==> Searching taps on GitHub...
==> Searching for similarly named formulae...
==> Searching taps...
Error: No formulae found in taps.
Installing python2 has failed!
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
```