fix(vim): work around coc-snippets issue
Looks like coc-snippets is no longer pulling this in, so manually add it
to vim-plug.

```
[Info 14:14:48] Using ultisnips directories: UltiSnips /Users/gib/.config/coc/ultisnips
[Info 14:14:48] Using ultisnips python command: pyx
Error on execute python script:
request error nvim_command - Vim(return):Error invoking 'python_execute_file' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "/var/folders/zt/kmdk_ldx5ygcrbz9k6px6kqh0000gn/T/coc.nvim-9418/coc-ultisnips-8xHkZ8obA3.py", line 271, in <module>
    from vimsnippets import get_comment_format
ModuleNotFoundError: No module named 'vimsnippets'
```

Refs: https://github.com/neoclide/coc-snippets/issues/126